### ISSUE TITLE
Error when running `terraform apply` a second time on a topic without config

### ISSUE THREAD

**Issue by Ahuri3** [Mongey/terraform-provider-kafka#35] opened 2018-11-28 19:28 UTC
First of all : creating a topic works fine, importing a topic also works, and finally deleting the topic works fine as well.

Here is my configuration : 
```
provider "kafka" {
  alias             = "kafk00"
  bootstrap_servers = ["kafk00:9092"]
  timeout           = 90000
}

resource "kafka_topic" "topic00" {
  provider           = "kafka.kafk00"

  name               = "topic00"
  replication_factor = 3
  partitions         = 1
}
```
I can run `terraform apply` with succes : 
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + kafka_topic.topic00
      id:                 <computed>
      name:               "topic00"
      partitions:         "1"
      replication_factor: "3"


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

kafka_topic.topic00: Creating...
  name:               "" => "topic00"
  partitions:         "" => "1"
  replication_factor: "" => "3"
kafka_topic.topic00: Creation complete after 0s (ID: topic00)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

Logs on the kafka server : 
```
2018-11-28T19:21:19.904533+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:19,904] INFO Topic creation Map(topic00-0 -> ArrayBuffer(3, 1, 2)) (kafka.zk.AdminZkClient)
2018-11-28T19:21:19.925127+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:19,924] INFO Replica loaded for partition topic00-0 with initial high watermark 0 (kafka.cluster.Replica)
2018-11-28T19:21:19.927577+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:19,927] INFO [Log partition=topic00-0, dir=/var/log/kafka/main] Loading producer state till offset 0 with message format version 2 (kafka.log.Log)
2018-11-28T19:21:19.928153+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:19,927] INFO [Log partition=topic00-0, dir=/var/log/kafka/main] Completed load of log with 1 segments, log start offset 0 and log end offset 0 in 1 ms (kafka.log.Log)
2018-11-28T19:21:19.931738+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:19,928] INFO Created log for partition topic00-0 in /var/log/kafka/main with properties {compression.type -> producer, message.format.version -> 2.1-IV2, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, message.downconversion.enable -> true, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 536870912, retention.ms -> 172800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
2018-11-28T19:21:19.932316+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:19,928] INFO [Partition topic00-0 broker=1] No checkpointed highwatermark is found for partition topic00-0 (kafka.cluster.Partition)
2018-11-28T19:21:19.932915+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:19,928] INFO Replica loaded for partition topic00-0 with initial high watermark 0 (kafka.cluster.Replica)
2018-11-28T19:21:19.933426+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:19,928] INFO Replica loaded for partition topic00-0 with initial high watermark 0 (kafka.cluster.Replica)
2018-11-28T19:21:19.933932+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:19,929] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions Set(topic00-0) (kafka.server.ReplicaFetcherManager)
2018-11-28T19:21:19.934465+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:19,929] INFO [ReplicaFetcherManager on broker 1] Added fetcher to broker BrokerEndPoint(id=3, host=de-00-kafk00-0002.node.consul:9092) for partitions Map(topic00-0 -> (offset=0, leaderEpoch=0)) (kafka.server.ReplicaFetcherManager)
2018-11-28T19:21:20.203266+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:20,202] WARN [ReplicaFetcher replicaId=1, leaderId=3, fetcherId=0] Based on replica's leader epoch, leader replied with an unknown offset in topic00-0. The initial fetch offset 0 will be used for truncation. (kafka.server.ReplicaFetcherThread)
2018-11-28T19:21:20.204245+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:21:20,204] INFO [Log partition=topic00-0, dir=/var/log/kafka/main] Truncating to 0 has no effect as the largest offset in the log is -1 (kafka.log.Log)

```

But if I run `terraform apply` again it will not only try to change the topic but will also fail : 
```
kafka_topic.topic00: Refreshing state... (ID: topic00)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ kafka_topic.topic00
      config.%:             "1" => "0"
      config.segment.bytes: "536870912" => ""


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

kafka_topic.topic00: Modifying... (ID: topic00)
  config.%:             "1" => "0"
  config.segment.bytes: "536870912" => ""
kafka_topic.topic00: Still modifying... (ID: topic00, 10s elapsed)
kafka_topic.topic00: Still modifying... (ID: topic00, 20s elapsed)
kafka_topic.topic00: Still modifying... (ID: topic00, 30s elapsed)
kafka_topic.topic00: Still modifying... (ID: topic00, 40s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* kafka_topic.topic00: 1 error(s) occurred:

* kafka_topic.topic00: Error waiting for topic (topic00) to become ready: couldn't find resource (21 retries)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

Logs on the kafka server : 
```
2018-11-28T19:22:40.501062+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:22:40,500] INFO Processing notification(s) to /config/changes (kafka.common.ZkNodeChangeNotificationListener)
2018-11-28T19:22:40.503525+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:22:40,503] INFO Processing override for entityPath: topics/topic00 with config: Map() (kafka.server.DynamicConfigManager)
2018-11-28T19:22:40.522534+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:22:40,522] INFO Processing notification(s) to /config/changes (kafka.common.ZkNodeChangeNotificationListener)
```

Finally : if I try to change the number of partitions or add some configuration it works flawlessly : 

New config :
```
resource "kafka_topic" "topic00" {
  provider           = "kafka.kafk00"

  name               = "topic00"
  replication_factor = 3
  partitions         = 3
  config = {
    cleanup.policy     = "compact"
    segment.bytes      = "104857600"
    compression.type   = "producer"
  }

}
```

Result : 
```
kafka_topic.topic00: Refreshing state... (ID: topic00)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ kafka_topic.topic00
      config.%:                "1" => "3"
      config.cleanup.policy:   "" => "compact"
      config.compression.type: "" => "producer"
      config.segment.bytes:    "536870912" => "104857600"
      partitions:              "1" => "3"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

kafka_topic.topic00: Modifying... (ID: topic00)
  config.%:                "1" => "3"
  config.cleanup.policy:   "" => "compact"
  config.compression.type: "" => "producer"
  config.segment.bytes:    "536870912" => "104857600"
  partitions:              "1" => "3"
kafka_topic.topic00: Modifications complete after 3s (ID: topic00)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```

Logs Kafka : 
```
2018-11-28T19:26:53.976255+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:53,976] INFO Processing notification(s) to /config/changes (kafka.common.ZkNodeChangeNotificationListener)
2018-11-28T19:26:53.978289+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:53,977] INFO Processing override for entityPath: topics/topic00 with config: Map(cleanup.policy -> compact, segment.bytes -> 104857600, compression.type -> producer) (kafka.server.DynamicConfigManager)
2018-11-28T19:26:54.038541+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,038] INFO Creating 2 partitions for 'topic00' with the following replica assignment: Map(2 -> ArrayBuffer(2, 3, 1), 1 -> ArrayBuffer(1, 2, 3)). (kafka.zk.AdminZkClient)
2018-11-28T19:26:54.039314+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,038] INFO Topic update Map(topic00-0 -> Vector(3, 1, 2), topic00-2 -> ArrayBuffer(2, 3, 1), topic00-1 -> ArrayBuffer(1, 2, 3)) (kafka.zk.AdminZkClient)
2018-11-28T19:26:54.065498+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,065] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions Set(topic00-1) (kafka.server.ReplicaFetcherManager)
2018-11-28T19:26:54.069196+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,069] INFO [Log partition=topic00-1, dir=/var/log/kafka/main] Loading producer state till offset 0 with message format version 2 (kafka.log.Log)
2018-11-28T19:26:54.070156+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,069] INFO [Log partition=topic00-1, dir=/var/log/kafka/main] Completed load of log with 1 segments, log start offset 0 and log end offset 0 in 1 ms (kafka.log.Log)
2018-11-28T19:26:54.070961+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,070] INFO Created log for partition topic00-1 in /var/log/kafka/main with properties {compression.type -> producer, message.format.version -> 2.1-IV2, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, message.downconversion.enable -> true, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> compact, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 104857600, retention.ms -> 172800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
2018-11-28T19:26:54.071654+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,070] INFO [Partition topic00-1 broker=1] No checkpointed highwatermark is found for partition topic00-1 (kafka.cluster.Partition)
2018-11-28T19:26:54.072341+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,070] INFO Replica loaded for partition topic00-1 with initial high watermark 0 (kafka.cluster.Replica)
2018-11-28T19:26:54.073007+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,070] INFO Replica loaded for partition topic00-1 with initial high watermark 0 (kafka.cluster.Replica)
2018-11-28T19:26:54.073666+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,070] INFO Replica loaded for partition topic00-1 with initial high watermark 0 (kafka.cluster.Replica)
2018-11-28T19:26:54.074291+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,071] INFO [Partition topic00-1 broker=1] topic00-1 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
2018-11-28T19:26:54.082191+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,081] INFO Replica loaded for partition topic00-2 with initial high watermark 0 (kafka.cluster.Replica)
2018-11-28T19:26:54.082967+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,081] INFO Replica loaded for partition topic00-2 with initial high watermark 0 (kafka.cluster.Replica)
2018-11-28T19:26:54.084792+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,084] INFO [Log partition=topic00-2, dir=/var/log/kafka/main] Loading producer state till offset 0 with message format version 2 (kafka.log.Log)
2018-11-28T19:26:54.085374+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,085] INFO [Log partition=topic00-2, dir=/var/log/kafka/main] Completed load of log with 1 segments, log start offset 0 and log end offset 0 in 2 ms (kafka.log.Log)
2018-11-28T19:26:54.086114+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,086] INFO Created log for partition topic00-2 in /var/log/kafka/main with properties {compression.type -> producer, message.format.version -> 2.1-IV2, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, message.downconversion.enable -> true, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> compact, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 104857600, retention.ms -> 172800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
2018-11-28T19:26:54.086842+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,086] INFO [Partition topic00-2 broker=1] No checkpointed highwatermark is found for partition topic00-2 (kafka.cluster.Partition)
2018-11-28T19:26:54.087375+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,086] INFO Replica loaded for partition topic00-2 with initial high watermark 0 (kafka.cluster.Replica)
2018-11-28T19:26:54.088184+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,087] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions Set(topic00-2) (kafka.server.ReplicaFetcherManager)
2018-11-28T19:26:54.089003+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,087] INFO [ReplicaFetcherManager on broker 1] Added fetcher to broker BrokerEndPoint(id=2, host=de-00-kafk00-0001.node.consul:9092) for partitions Map(topic00-2 -> (offset=0, leaderEpoch=0)) (kafka.server.ReplicaFetcherManager)
2018-11-28T19:26:54.388024+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,387] WARN [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Based on replica's leader epoch, leader replied with an unknown offset in topic00-2. The initial fetch offset 0 will be used for truncation. (kafka.server.ReplicaFetcherThread)
2018-11-28T19:26:54.389008+00:00 kafk00 daemon info kafka-server-start.sh[3819]: [2018-11-28 19:26:54,388] INFO [Log partition=topic00-2, dir=/var/log/kafka/main] Truncating to 0 has no effect as the largest offset in the log is -1 (kafka.log.Log)
```

I believe this is not the intended behavior

**Comment by Mongey** [comment] 2018-11-28 23:02
Hey @Ahuri3, thanks for the thorough bug report. 

It looks like this is an error in how default topic configs are handled. I've been able reproduce the issues over in https://github.com/Mongey/terraform-provider-kafka/pull/36 , should have a fix soon.

**Comment by Mongey** [comment] 2018-11-28 23:49
I've dug around a bit more. It seems that there has been a change in how Kafka reports default topic configs.

In Kafka 1.0 setting `log.segments.bytes` on the broker would report back `segments.bytes` as a default setting in the [`DescribeConfigs Response (Version: 0)`](https://kafka.apache.org/protocol#The_Messages_DescribeConfigs). The provider would filter out defaults, and there would be no change reported to Terraform.

In Kafka 2.0 this is reported back as a non-default config in the `DescribeConfigs Response (Version: 0)` 😭

`DescribeConfigs Response (Version: 2)` includes a `usesconfig_source` enum that can be used to determine if the config is really a default, but it looks like `DescribeConfigs Response (Version: 2)` will need to be implemented in the upstream Kafka Client: [Shopify/sarama](https://github.com/Shopify/sarama) before we can fix it here.

**Comment by Mongey** [comment] 2018-11-29 17:00
👋 @Ahuri3 I've implemented the new protocols, but it'll take a while to get merged upstream.

If you want to try out the changes, and see if they work for you, you can get a binary from the CI system from #36 [here](
https://218-103748731-gh.circle-artifacts.com/0/terraform-provider-kafka)

**Comment by Ahuri3** [comment] 2018-11-30 11:05
Thank you so much for the lightning fast response !

I will try it out and post my results as soon as possible.

**Closed** 2018-12-05 10:08 UTC
Labels: bug
